#include "comp.h"


void Comp_Init(void)
{
    RCC->AHB2ENR |= RCC_AHB2ENR_GPIOAEN;
    RCC->AHB2ENR |= RCC_AHB2ENR_GPIOBEN;
    RCC->APB2ENR |= RCC_APB2ENR_SYSCFGEN;

    // PA1, PA7, PB0 Analog Mode 설정
    GPIOA->MODER &= ~(GPIO_MODER_MODE1_Msk | GPIO_MODER_MODE7_Msk);
    GPIOA->MODER |= GPIO_MODER_MODE1 | GPIO_MODER_MODE7;
    GPIOB->MODER &= ~GPIO_MODER_MODE0_Msk;
    GPIOB->MODER |= GPIO_MODER_MODE0;

    GPIOA->PUPDR &=~(GPIO_PUPDR_PUPD1_Msk | GPIO_PUPDR_PUPD7_Msk);
    GPIOB->PUPDR &=~ GPIO_PUPDR_PUPD0_Msk;

    COMP1->CSR &=~ COMP_CSR_INPSEL;
    COMP2->CSR &=~ COMP_CSR_INPSEL;
    COMP4->CSR &=~ COMP_CSR_INPSEL;


}